# This is a basic workflow to help you get started with Actions

name: CI to Docker Hub - eureka

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: Abhinav2


  # # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a job called "build"

  compile:
    runs-on: ubuntu-latest
    name: Running Java ${{ matrix.java }} compile
    steps:

      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Compile code
        working-directory : ./eureka/
        run: mvn compile

  docker-login:
    # The type of runner that the job will run on
    needs: [compile]
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1



  build-and-push-to-dockerhub-eureka:
    needs: [docker-login]
    runs-on: ubuntu-latest
    steps:

      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./eureka
          file: ./eureka/Dockerfile
          push: true
          tags: ${{secrets.DOCKER_HUB_USERNAME }}/tutor-eureka-actions:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}


  Pull-from-dockerhub-and-run-eureka:
    needs: [build-and-push-to-dockerhub-eureka]
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Image Pull
        run: docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/tutor-eureka-actions:latest
      - name: Show Image
        run: docker image ls
      - name: Docker Run
        run: docker run -itd ${{ secrets.DOCKER_HUB_USERNAME }}/tutor-eureka-actions:latest

